version: "3.8"
services:
    app:
        build:
            context: https://github.com/OrhayBenaim/automatic_garden.git
            dockerfile: app/Dockerfile
        ports:
            - "80:3000"
    nginx:
        restart: always
        build:
            context: https://github.com/OrhayBenaim/automatic_garden.git
            dockerfile: nginx/Dockerfile
        ports:
            - "9999:80"